<a href="https://colab.research.google.com/github/jakubdaron/MTR_optymalizacja/blob/main/Problem_RPQ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [21]:
import random
import numpy as np

def generate_sorted_rpq_table(n, F):
    rpq = []
    # generate random r, p, q values
    for i in range(n):
        r = random.randint(0, n*F)
        p = random.randint(1, 50)
        q = random.randint(0, n*F)
        rpq.append([r, p, q])

    # sort rpq table in increasing order of r values
    rpq = np.array(rpq)
    sorted_rpq = rpq[rpq[:, 0].argsort()]
    #sorted_rpq = np.array([[6, 4, 2], [6, 8, 3], [10, 2, 3], [12, 3, 0]])
    return sorted_rpq

def add_and_sort_bufor(sorted_rpq, iteration, bufor_queue):
    bufor = sorted_rpq[iteration].tolist()
    bufor_queue.append(bufor)
    bufor_queue = np.array(bufor_queue)

    # sort bufor_queue in decreasing order of q values
    sorted_bufor = bufor_queue[bufor_queue[:, 2].argsort()[::-1]]
    bufor_queue = sorted_bufor.tolist()
    return bufor_queue

def optimise_function(sorted_rpq, n):
    iteration = 0
    bufor_queue = []
    current_task = 0
    time = 0
    end_iteration = 0
    end_def = 0

    while end_def == 0:
        #print(current_task)
        if time == sorted_rpq[iteration, 0]:
            while True:
                bufor_queue = add_and_sort_bufor(sorted_rpq, iteration, bufor_queue)
                if iteration < n-1:
                    iteration += 1
                else:
                    end_iteration = 1

                if sorted_rpq[iteration, 0] != sorted_rpq[iteration-1, 0]:
                    break

        if current_task <= 0 and bufor_queue:
            current_task = bufor_queue[0][1]
            bufor_queue.pop(0)

        print(f"time: {time}, current_task: {current_task}, bufor_queue: {bufor_queue}")
        #print(f"time: {time}, current_task: {current_task}")
        time += 1
        current_task -= 1

        if end_iteration == 1:
            if current_task == 0 and len(bufor_queue) == 0:
                end_def = 1

if __name__ == "__main__":
    F = 17
    n = 20
    sorted_rpq = generate_sorted_rpq_table(n, F)
    print(sorted_rpq)
    optimise_function(sorted_rpq, n)

[[ 20  39 317]
 [ 76  49  15]
 [121  10 300]
 [136   4 183]
 [138  48 175]
 [142  11 280]
 [144  41 121]
 [172  16 190]
 [172  31 179]
 [191  30 171]
 [192  38 289]
 [195  45 246]
 [199  38 129]
 [210  38  51]
 [217   5 192]
 [232  45  98]
 [283  50 328]
 [285  48 306]
 [326  43 115]
 [334  18 339]]
time: 0, current_task: 0, bufor_queue: []
time: 1, current_task: -1, bufor_queue: []
time: 2, current_task: -2, bufor_queue: []
time: 3, current_task: -3, bufor_queue: []
time: 4, current_task: -4, bufor_queue: []
time: 5, current_task: -5, bufor_queue: []
time: 6, current_task: -6, bufor_queue: []
time: 7, current_task: -7, bufor_queue: []
time: 8, current_task: -8, bufor_queue: []
time: 9, current_task: -9, bufor_queue: []
time: 10, current_task: -10, bufor_queue: []
time: 11, current_task: -11, bufor_queue: []
time: 12, current_task: -12, bufor_queue: []
time: 13, current_task: -13, bufor_queue: []
time: 14, current_task: -14, bufor_queue: []
time: 15, current_task: -15, bufor_queue: []
